# docker-compose-dev.yml
services:

  backend:
    build:
      context: .
      args:
        DEBUG: "true"
    env_file:
      - .env.sample
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.1
    restart: always
    env_file:
      - .env.sample
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "devdb", "-U", "devuser"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
