name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Use env sample for tests
        run: cp backend/.env.sample backend/.env

      - name: Run Tests
        run: docker compose run --rm backend sh -c "python manage.py test"

      - name: Run Lint
        run: docker compose run --rm backend sh -c "flake8"
