name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env with dummy values
        run: |
          echo "POSTGRES_DB=testdb" > .env
          echo "POSTGRES_USER=testuser" >> .env
          echo "POSTGRES_PASSWORD=testpass" >> .env
          echo "DB_NAME=testdb" >> .env
          echo "DB_USER=testuser" >> .env
          echo "DB_PASS=testpass" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Build and run containers
        run: docker compose up -d

      - name: Run tests
        run: docker compose run --rm backend sh -c "python manage.py test"

      - name: Shutdown containers
        if: always()
        run: docker compose down -v
