# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create dummy .env file
        run: |
          echo "POSTGRES_DB=dummydb" >> .env
          echo "POSTGRES_USER=dummyuser" >> .env
          echo "POSTGRES_PASSWORD=dummypass" >> .env
          echo "DB_NAME=dummydb" >> .env
          echo "DB_USER=dummyuser" >> .env
          echo "DB_PASS=dummypass" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start containers
        run: docker compose up -d

      - name: Run Django tests
        run: docker compose run --rm backend sh -c "python manage.py test"

      - name: Tear down
        if: always()
        run: docker compose down -v
